### ISSUE TITLE
503 error when visiting wp-admin

### ISSUE THREAD

**Issue by centrino97** [CreativForm/serbian-transliteration#3]
Choose the type of Issue

- [ ] Bug Report

- **Expected behavior**: No expected changes after the update on 21. of February.
- **Actual behavior**: 503 error, when trying to access shiningego.rs/wp-admin, and this started since last update. Also 
![WhatsApp Image 2024-02-26 at 13 47 16](https://github.com/InfinitumForm/serbian-transliteration/assets/161331671/d02a22c9-335b-49f8-9168-1f89ce90a2c3)

- **Steps to reproduce the issue**: visiting shiningego.rs/wp-admin we hit 503 page unless we deactivate transliteration plugin.
- **WordPress version**: 6.4.3
- **Plugin version**: 1.12.13
- **Any relevant error messages or logs**
[error_log-20240224.gz](https://github.com/InfinitumForm/serbian-transliteration/files/14405901/error_log-20240224.gz)

## Additional Context
Just a single member of our team can easily access the wp-admin, other people using the same credentials cannot. Hosting says that the problem is within the plugin, or compatibility with LiteSpeed Cache 6.1 version.

**Comment by InfinitumForm** [comment]
Hello,

I apologize for the late reply (a couple of months later).

This problem was due to a memory leak which was fixed after that. Now everything works as it should.

If you want, you can download the [new BETA version](https://github.com/InfinitumForm/serbian-transliteration/releases/tag/v2.0.0-beta) and try how it works.

Best regards!

**Comment by InfinitumForm** [comment]
New version is released and solve the problems.
